### ISSUE TITLE
Parametrize Message Roles

### ISSUE THREAD

**Issue by carbaj03** [xebia-functional/xef#200]
Could other roles like User (human) and Assistant be used?
I suppose that the exclusive use of the System role affects the result that the LLM's could return.

I don't know if it is something exclusive to OpenAi or if it can be generic for more LLM's.

```kotlin
private suspend fun callChatEndpoint(
    prompt: String,
    model: LLM.Chat,
    user: String,
    n: Int,
    temperature: Double,
    bringFromContext: Int,
    minResponseTokens: Int
  ): List<String> {
    val role: String = Role.system.name
    val promptWithContext: String =
      promptWithContext(prompt, bringFromContext, model.modelType, minResponseTokens)
    val messages: List<Message> = listOf(Message(role, promptWithContext))
    val maxTokens: Int = checkTotalLeftChatTokens(messages, model)
    val request =
      ChatCompletionRequest(
        model = model.name,
        user = user,
        messages = messages,
        n = n,
        temperature = temperature,
        maxTokens = maxTokens
      )
    return AIClient.createChatCompletion(request).choices.mapNotNull { it.message?.content }
  }
```

**Comment by raulraja** [comment]
We are not exposing the full ChatCompletion interface, so the role is hard coded. It's a single message rather than a chat conversation, but we still rely on the chat models. The role can be passed as parameters with a default value up to the `prompt` and `promptMessage` functions where the default value is `Role.system.name`.

@carbaj03 If you want to propose that in a PR, we can promote it to the default value parameter

**Comment by carbaj03** [comment]
With the last addition of Memory and ConversationId, I guess that we solve the issue of having to pass Role as parameters since the own library takes care of managing the Chat base conversation. I'm right?

**Comment by raulraja** [comment]
If we assume that the chat conversation is just between two entities assistant and user for now then yes.

**Comment by raulraja** [comment]
@carbaj03 in the latest alphas there is better support for prompt and the messages they are composed of.
For example you can now have fine control of what gets sent to the LLM like this:
```kotlin
private suspend fun createPRDescription(summary: String): String =
    chat.promptMessage(
      prompt =
        Prompt {
          +system("Create Pull Request Description")
          +assistant(
            "I will roleplay as an expert software engineer implementing a service to read a .diff file from a URL and create a Pull Request description with an automatically inferred user intent."
          )
          +assistant(
            "I will use the following program to return a Pull Request description to the user:"
          )
          +systemPrompt()
          +user("Set Summary = $summary")
          +user("CreatePRDescription()")
          +assistant(
            "A great, concise and neutral toned Pull Request description for this summary is:"
          )
        },
      scope = scope
    )
```
