### ISSUE TITLE
Keep ggml and llama.cpp dependencies up to date.

### ISSUE THREAD

**Issue by raulraja** [xebia-functional/xef#215]
Currently, the llama.cpp binaries are stored in the resources folder for what looks now an old version.

I noticed that when trying to load many of the ggml model files from huggingface many of them fail. We don't know if is due to these binaries being outdated. Ideally, we can point to a release version we compile automatically in CI or we fetch the binaries if they are published somewhere.

<img width="292" alt="Screenshot 2023-07-02 at 20 03 02" src="https://github.com/xebia-functional/xef/assets/456796/321532f3-ba26-414c-8e2f-8b73bc2c0178">

For example:
```kotlin
package com.xebia.functional.xef.auto.gpt4all

import com.xebia.functional.gpt4all.GPT4All
import com.xebia.functional.gpt4all.LLModel
import com.xebia.functional.gpt4all.getOrThrow
import com.xebia.functional.gpt4all.huggingFaceUrl
import com.xebia.functional.xef.auto.PromptConfiguration
import com.xebia.functional.xef.auto.ai
import com.xebia.functional.xef.auto.llm.openai.OpenAI
import com.xebia.functional.xef.pdf.pdf
import java.nio.file.Path

suspend fun main() {
  //TheBloke/mpt-30B-chat-GGML
  val userDir = System.getProperty("user.dir")
  val path = "$userDir/models/gpt4all/Wizard-Vicuna-13B-Uncensored.ggmlv3.q8_0.bin"
  val url = "https://huggingface.co/TheBloke/Wizard-Vicuna-13B-Uncensored-GGML/resolve/main/Wizard-Vicuna-13B-Uncensored.ggmlv3.q8_0.bin"
  val modelType = LLModel.Type.GPTJ
  val modelPath: Path = Path.of(path)
  val GPT4All = GPT4All(url, modelPath, modelType)

  println("🤖 GPT4All loaded: $GPT4All")

  val pdfUrl = "https://kotlinlang.org/docs/kotlin-reference.pdf"

  /**
   * Uses internally [HuggingFaceLocalEmbeddings] default of "sentence-transformers", "msmarco-distilbert-dot-v5"
   * to provide embeddings for docs in contextScope.
   */

  ai {
    println("🤖 Loading PDF: $pdfUrl")
    contextScope(pdf(pdfUrl)) {
      println("🤖 Context loaded: $context")
      GPT4All.use { gpT4All: GPT4All ->
        println("🤖 Generating prompt for context")
        while (true) {
          println("🤖 Enter your prompt: ")
          val userInput = readlnOrNull() ?: break
          val prompt = gpT4All.promptMessage(
            userInput,
            promptConfiguration = PromptConfiguration {
              docsInContext(2)
            })
          println("🤖 Response: $prompt")
        }
      }
    }
  }.getOrThrow()
}
```
```
Downloading: 100% |████████████████████████████████████████| Wizard-Vicuna-13B-Uncensored.ggmlv3.q8_0.bin
gptj_model_load: loading model from '/Users/raulraja/workspace/langchain4k/models/gpt4all/Wizard-Vicuna-13B-Uncensored.ggmlv3.q8_0.bin' - please wait ...
gptj_model_load: invalid model file '/Users/raulraja/workspace/langchain4k/models/gpt4all/Wizard-Vicuna-13B-Uncensored.ggmlv3.q8_0.bin' (bad magic)
```

**Comment by raulraja** [comment]
When switching to LLAMA type similar error messages:
```
error loading model: unknown (magic, version) combination: 67676a74, 00000003; is this really a GGML file?
llama_init_from_file: failed to load model
```

**Comment by jackcviers** [comment]
Suggestion:

Put user models in a user home dotfile and usr/share fallback. Package as native tarball extracting to usr/share and usr/local/bin.

Automate pulling models from hugging face in ci and releasing models that work as curated native subpackages.

Models are going to be constantly changing and the pace of change will be extremely rapid for the foreseeable future in the AI space. We should crawl available models and test, and repackage them for xef using an automatic ci process to allow users to use xef with the least amount of friction possible.

**Comment by raulraja** [comment]
It looks like llama.cpp does not package the release as binaries but this lib already packages all binaries https://github.com/abetlen/llama-cpp-python/releases, they could be extracted from their releases and renamed based on the architecture expectations we have now.
