### ISSUE TITLE
Unexpected (?) behaviour of `LocalVectorStore`'s `addMemories`

### ISSUE THREAD

**Issue by victorcrrd** [xebia-functional/xef#262]
I think that the current implementation of `addMemories` for the `LocalVectorStore` class is not what we would expect. Namely, the [actual code](https://github.com/xebia-functional/xef/blob/main/core/src/commonMain/kotlin/com/xebia/functional/xef/vectorstores/LocalVectorStore.kt#L35) updates the previous state's memories as `prevState.orderedMemories + memories.groupBy { it.conversationId }`, however, for a given `conversationId` it would just replace the list of `Memory` to the one in value `memories`, "forgetting" about the ones in `prevState.orderedMemories` for that same `conversationId`. The following image shows the problem:
<img width="468" alt="Captura de pantalla 2023-07-20 a las 15 05 34" src="https://github.com/xebia-functional/xef/assets/24816566/016a28ec-31d5-4d80-849e-f787feb37d6c">

**Comment by javipacheco** [comment]
Yes @victorcrrd 

I saw the same problem this morning in my PR. I'm working on it
