### ISSUE TITLE
Parameterise OpenAIToken, Timeout and RetryConfig

### ISSUE THREAD

**Issue by anamariamv** [xebia-functional/xef#361]
In previous work we had a need to influence the configuration of our retry methods and timeouts since sometimes for long or complex tasks the reply from the LLM can take quite some time to solve.

So we need to be able to configure the CoreAIScope  to take into account custom configurations. 

In addition we don't want to force library authors, or end-users to setup environment configurations for the OpenAIToken so we should also parameterise this in a Config class rather than the current hard-coded environment variable.  https://github.com/xebia-functional/xef/blob/6831f30d6440138bd873bf446a2b67929556bc44/openai/src/commonMain/kotlin/com/xebia/functional/xef/auto/llm/openai/OpenAI.kt#L47

**Comment by tomascayuelas** [comment]
With the changes that we planning to do maybe this issue pass to be obsolete... What do you think @anamariamv , can we close?
