### ISSUE TITLE
Azure AI | Machine Learning Studio

### ISSUE THREAD

**Issue by anamariamv** [xebia-functional/xef#362]
We have a temporal Azure subscription to deploy LLMs in azure.

We want to deploy some models from the [Model Catalog](https://ml.azure.com/model/catalog) and interact with them via the HTTP API from [Xef.ai](http://xef.ai/)

Some proposed models:
One open source model: databricks-dolly-v2-12b 
One hugging face model: microsoft-dialogpt-large 
One openAI model: gpt-4  (we are waiting for access to Azure OpenAI Service right now)

**Comment by ishaan-jaff** [comment]
Hi @anamariamv (cc @raulraja ) I’m the maintainer of LiteLLM (abstraction to call 100+ LLMs)- we allow you to create a proxy server to call 100+ LLMs, and I think it can solve your problem (I'd love your feedback if it does not)

Try it here: https://docs.litellm.ai/docs/proxy_server
https://github.com/BerriAI/litellm

## Using LiteLLM Proxy Server
```python
import openai
openai.api_base = "http://0.0.0.0:8000/" # proxy url
print(openai.ChatCompletion.create(model="test", messages=[{"role":"user", "content":"Hey!"}]))
```

## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```


Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

**Comment by raulraja** [comment]
@ishaan-jaff thank you for reaching out. I looked into `litellm` and I think it can indeed solve our problem of reducing the number of integrations on our backend when talking to different models. the callback API can also help us integrate with our own LLM tools. I'll check it out in the next few weeks and will reach out if we run into any issues. thank you!

**Comment by ishaan-jaff** [comment]
that's awesome ! please let me know if I can help in an way

**Comment by tomascayuelas** [comment]
@anamariamv can we close this task?
