### ISSUE TITLE
Support withFunctions in GPT4All

### ISSUE THREAD

**Issue by anamariamv** [xebia-functional/xef#377]
The current integration of GPT4All models doesn't support the ChatWithFunctions  or the prompts with deserialisation. So it's not possible to deserialise a response into a Kotlin data class, for example. 

In a previous version, we have a previous version to instruct the LLM to produce serializable json based on a schema. This was deleted here:

https://github.com/xebia-functional/xef/pull/186

The objective of this ticket is to see if makes sense to bring this functionality to the local models.

**Comment by tomascayuelas** [comment]
We can close this task.
