### ISSUE TITLE
docs/intro.md doesn't exist anymore

### ISSUE THREAD

**Issue by lenntt** [xebia-functional/xef#626]
This very promising link in the README.md with a 'quick introduction', isnt working anymore
https://github.com/xebia-functional/xef?tab=readme-ov-file#-quick-introduction

It got removed earlier (for being outdated)
https://github.com/xebia-functional/xef/commit/1d642693f2b66d1ecd706b632c98ae6535383dbf

Is there another 'quick introduction somehwere else, maybe?

**Comment by Montagon** [comment]
Thanks for seeing that 👍
